In [1]:
import numpy as np

# Basic numpy arrays

In [2]:
np.array([1,2,3,4])

array([1, 2, 3, 4])

In [3]:
a = np.array([1,2,3,4])
a 

array([1, 2, 3, 4])

In [4]:
b = np.array([0,.5,1,1.5,2])
b 

array([0. , 0.5, 1. , 1.5, 2. ])

In [5]:
a[0], a[1]

(1, 2)

In [6]:
b[1], b[b.size-1]

(0.5, 2.0)

In [7]:
a[0:-1]

array([1, 2, 3])

In [8]:
a[::2]

array([1, 3])

In [9]:
#b[1],b[2],b[-1] == b[[1,2,-1]]
b[[1,2,-1]]

array([0.5, 1. , 2. ])

# Array types

In [10]:
a

array([1, 2, 3, 4])

In [11]:
a.dtype

dtype('int32')

In [12]:
b

array([0. , 0.5, 1. , 1.5, 2. ])

In [13]:
b.dtype

dtype('float64')

In [14]:
c = np.array([1,5,6,9], dtype='int8')
c

array([1, 5, 6, 9], dtype=int8)

In [15]:
d = np.array(['a','b'])
d.dtype

dtype('<U1')

# Dimentions and shapes

In [16]:
A = np.array([
    [1,2,3],
    [4,5,6]
])
A 

array([[1, 2, 3],
       [4, 5, 6]])

In [17]:
A.ndim

2

In [18]:
A.shape

(2, 3)

In [19]:
A.size

6

In [20]:
B = np.array([
    [
        [11,12,10],
        [9,8,7]        
    ],
    [
        [6,5,4],
        [1,8,4]        
    ]
])

In [21]:
B

array([[[11, 12, 10],
        [ 9,  8,  7]],

       [[ 6,  5,  4],
        [ 1,  8,  4]]])

In [22]:
B.shape

(2, 2, 3)

In [23]:
B.ndim

3

In [24]:
B.size

12

# Indexing and slicing matrices

In [25]:
A = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

In [26]:
A[1]

array([4, 5, 6])

In [27]:
A[1][0]

4

### A[d1,d2,d3,d4]

In [28]:
A[0:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [29]:
A[:,:2]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [30]:
A[:2,:2]

array([[1, 2],
       [4, 5]])

In [31]:
A[:2,2:]

array([[3],
       [6]])

In [32]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [33]:
A[1] = np.array([5,5,5])

In [34]:
A

array([[1, 2, 3],
       [5, 5, 5],
       [7, 8, 9]])

In [35]:
A[2] = 5

In [36]:
A

array([[1, 2, 3],
       [5, 5, 5],
       [5, 5, 5]])

# Summary Statistics

In [37]:
a= np.array([1,5,6,9])

In [38]:
a.sum()

21

In [39]:
a.mean()

5.25

In [40]:
a.std()

2.8613807855648994

In [41]:
A = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

In [42]:
A.sum()

45

In [43]:
# adds by columns
A.sum(axis=0)

array([12, 15, 18])

In [44]:
#adds by rows
A.sum(axis=1)

array([ 6, 15, 24])

In [45]:
A.mean(axis=0)

array([4., 5., 6.])

In [46]:
A.mean(axis=1)

array([2., 5., 8.])

In [47]:
A.std(axis=0)

array([2.44948974, 2.44948974, 2.44948974])

In [48]:
A.std(axis=1)

array([0.81649658, 0.81649658, 0.81649658])

# Broadcasting and vectorized operations

In [49]:
c = np.arange(4)

In [50]:
c

array([0, 1, 2, 3])

In [51]:
c+10

array([10, 11, 12, 13])

In [52]:
c

array([0, 1, 2, 3])

In [53]:
c += 10

In [54]:
c

array([10, 11, 12, 13])

In [55]:
l = [0,1,2,3]

In [56]:
[i *10 for i in l]

[0, 10, 20, 30]

In [57]:
a + l

array([ 1,  6,  8, 12])

In [58]:
a * l 

array([ 0,  5, 12, 27])

# Boolean arrays

In [59]:
a = np.arange(4)

In [60]:
a 

array([0, 1, 2, 3])

In [61]:
a[[0,-1]]

array([0, 3])

In [62]:
a[[True, False, False,True]]

array([0, 3])

In [63]:
a>=2

array([False, False,  True,  True])

In [64]:
a[a>=2]

array([2, 3])

In [65]:
a.mean()

1.5

In [66]:
a[a > a.mean()]

array([2, 3])

In [67]:
a[~(a > a.mean())]

array([0, 1])

In [68]:
a[(a == 0) | (a == 1)]

array([0, 1])

In [69]:
a[(a <= 2) & (a % 2 == 0)]

array([0, 2])

In [70]:
A = np.random.randint(100, size=(3,3))

In [71]:
A

array([[74, 20, 13],
       [39, 27, 64],
       [34, 17, 87]])

In [72]:
A[A > 20]

array([74, 39, 27, 64, 34, 87])

In [73]:
A[A == 53] = 21

In [74]:
A

array([[74, 20, 13],
       [39, 27, 64],
       [34, 17, 87]])

# Linear Algebra

In [75]:
A = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

In [76]:
B = np.array([
    [6,5],
    [4,3],
    [2,1]
])

In [77]:
A.dot(B)

array([[20, 14],
       [56, 41],
       [92, 68]])

In [78]:
B.T

array([[6, 4, 2],
       [5, 3, 1]])

In [81]:
A @ B

array([[20, 14],
       [56, 41],
       [92, 68]])

In [82]:
B.T @ A

array([[36, 48, 60],
       [24, 33, 42]])

# Size of object in memory

### int, float

In [83]:
import sys

In [84]:
sys.getsizeof(1)

28

In [85]:
sys.getsizeof(10**1000)

468

In [86]:
sys.getsizeof(10.5)

24

In [87]:
np.dtype(int).itemsize

4

In [88]:
np.dtype(float).itemsize

8

### Lists

In [89]:
sys.getsizeof([1])

72

In [90]:
np.array([1]).nbytes

4

### Performance

In [91]:
l = list(range(1000))

In [92]:
ll = np.arange(1000)

In [93]:
%time np.sum(ll**2)

Wall time: 0 ns


332833500

In [94]:
%time sum([x**2 for x in l])

Wall time: 0 ns


332833500

# Useful numpy functions

### Random

In [95]:
np.random.random(size=2)

array([0.88740792, 0.48914185])

In [96]:
np.random.normal(size=2)

array([-1.01580942,  1.67114628])

In [99]:
np.random.rand(2,4)*100

array([[82.99311943, 31.52017533, 88.96962559, 65.40199123],
       [27.19921496, 75.7315013 , 41.18863623, 47.40527792]])

### Arange

In [100]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [101]:
np.arange(5,10)

array([5, 6, 7, 8, 9])

In [102]:
np.arange(0,1,.1)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

### Reshape

In [103]:
np.arange(10).reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [104]:
np.arange(10).reshape(5,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

### linspace

In [105]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [106]:
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [107]:
np.linspace(0,1,20,False)

array([0.  , 0.05, 0.1 , 0.15, 0.2 , 0.25, 0.3 , 0.35, 0.4 , 0.45, 0.5 ,
       0.55, 0.6 , 0.65, 0.7 , 0.75, 0.8 , 0.85, 0.9 , 0.95])

### zeros, ones, empty

In [108]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [109]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [110]:
np.zeros((3,3), dtype=np.int)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [111]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [113]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [114]:
np.ones((3,3), dtype=np.int)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [115]:
np.empty(5)

array([1., 1., 1., 1., 1.])

In [117]:
np.empty((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

### Identity and eye

In [118]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [119]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [120]:
np.eye(8,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [121]:
np.eye(8,4, k=1)

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [122]:
np.eye(8,4, k=3)

array([[0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [123]:
"Hello World"[6]

'W'